### ISSUE TITLE
Symbol completions inside tidyverse functions

### ISSUE THREAD

**Issue by cpeccei** [jonclayden/R-Nova#3]
Great work on the R-Nova extension, thank you @jonclayden!

Is there a way to get symbol completions working inside tidyverse functions? For example, when I'm defining `d2` below I'd like to be able to type `my` then hit TAB and have `my_variable` show up in the completion list. 

```
d <- tibble(my_variable = 1:10)
d2 <- d %>% mutate(my_variable = my_variable * 2)
```

**Comment by jonclayden** [comment]
Hi, and thanks for raising this. If you haven't tried enabling language server support yet (via the extension's settings), I would suggest trying that, as it does add some dynamic autocomplete functionality. Note that you'll need to have the `languageserver` package installed before enabling this option, for it to work.

**Comment by cpeccei** [comment]
Thank you for the suggestion. I enabled language server support and now I do get completions inside tidyverse functions (as well as lots of other linting, which is nice).

One question if you have time: why doesn't the regex on [line 318 of R.xml](https://github.com/jonclayden/R-Nova/blob/a03d5827361b8692479e3c4839026d7b61c40269/R-Nova.novaextension/Syntaxes/R.xml#L318) match variables inside tidyverse functions and create symbols from them? It looks like it should work.

Thanks again, and feel free to close this issue.

**Comment by jonclayden** [comment]
The argument will match via line 206, not 318, because it's part of a call, and there's no symbolication there. Ultimately there's too much state needed for regexes alone to handle this properly, because we wouldn't want all named arguments to become symbols, and one needs to know the contents of a given tibble in order to provide the correct completions, which really requires full parsing.

I'm glad the language server support helps, though.
